// Code generated by schemacompiler. DO NOT EDIT.

package gentest

import (
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"slices"
	"unicode/utf8"

	"github.com/ogen-go/schemacompiler/opt"
)

// Nickname has an unenforced kind dispatch: nothing generated selects a branch, so every alternative is admitted.
type Nickname opt.Nullable[string]

// MarshalJSON implements json.Marshaler.
func (v Nickname) MarshalJSON() ([]byte, error) {
	return opt.Nullable[string](v).MarshalJSON()
}

// UnmarshalJSON implements json.Unmarshaler.
func (v *Nickname) UnmarshalJSON(data []byte) error {
	return (*opt.Nullable[string])(v).UnmarshalJSON(data)
}

// Pet is a pet.
type Pet struct {
	Name     string                 `json:"name"`
	Age      opt.Opt[int64]         `json:"age,omitzero"`
	Nickname opt.Nullable[Nickname] `json:"nickname"`
	Status   opt.Opt[Status]        `json:"status,omitzero"`
	Tags     opt.Opt[[]Tag]         `json:"tags,omitzero"`
	Parent   opt.Opt[*Pet]          `json:"parent,omitzero"`
	Shape    opt.Opt[Shape]         `json:"shape,omitzero"`
	At       opt.Opt[Point]         `json:"at,omitzero"`
	// AdditionalProps holds the properties no field and no pattern covers.
	AdditionalProps map[string]any
}

// MarshalJSON implements json.Marshaler.
func (s Pet) MarshalJSON() ([]byte, error) {
	b := []byte{'{'}
	n := 0
	var err error
	if b, err = encodeKey(b, &n, "name"); err != nil {
		return nil, err
	}
	{
		d, err := json.Marshal(s.Name)
		if err != nil {
			return nil, fmt.Errorf("encode %q: %w", "name", err)
		}
		b = append(b, d...)
	}
	if v, ok := s.Age.Get(); ok {
		if b, err = encodeKey(b, &n, "age"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "age", err)
			}
			b = append(b, d...)
		}
	}
	if b, err = encodeKey(b, &n, "nickname"); err != nil {
		return nil, err
	}
	{
		d, err := json.Marshal(s.Nickname)
		if err != nil {
			return nil, fmt.Errorf("encode %q: %w", "nickname", err)
		}
		b = append(b, d...)
	}
	if v, ok := s.Status.Get(); ok {
		if b, err = encodeKey(b, &n, "status"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "status", err)
			}
			b = append(b, d...)
		}
	}
	if v, ok := s.Tags.Get(); ok {
		if b, err = encodeKey(b, &n, "tags"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "tags", err)
			}
			b = append(b, d...)
		}
	}
	if v, ok := s.Parent.Get(); ok {
		if b, err = encodeKey(b, &n, "parent"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "parent", err)
			}
			b = append(b, d...)
		}
	}
	if v, ok := s.Shape.Get(); ok {
		if b, err = encodeKey(b, &n, "shape"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "shape", err)
			}
			b = append(b, d...)
		}
	}
	if v, ok := s.At.Get(); ok {
		if b, err = encodeKey(b, &n, "at"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "at", err)
			}
			b = append(b, d...)
		}
	}
	for _, k := range sortedKeys(s.AdditionalProps) {
		if b, err = encodeKey(b, &n, k); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(s.AdditionalProps[k])
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", k, err)
			}
			b = append(b, d...)
		}
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *Pet) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var out Pet
	if v, ok := raw["name"]; ok {
		if err := json.Unmarshal(v, &out.Name); err != nil {
			return fmt.Errorf("decode %q: %w", "name", err)
		}
		delete(raw, "name")
	} else {
		return fmt.Errorf("missing required property %q", "name")
	}
	if v, ok := raw["age"]; ok {
		if err := json.Unmarshal(v, &out.Age); err != nil {
			return fmt.Errorf("decode %q: %w", "age", err)
		}
		delete(raw, "age")
	}
	if v, ok := raw["nickname"]; ok {
		if err := json.Unmarshal(v, &out.Nickname); err != nil {
			return fmt.Errorf("decode %q: %w", "nickname", err)
		}
		delete(raw, "nickname")
	} else {
		return fmt.Errorf("missing required property %q", "nickname")
	}
	if v, ok := raw["status"]; ok {
		if err := json.Unmarshal(v, &out.Status); err != nil {
			return fmt.Errorf("decode %q: %w", "status", err)
		}
		delete(raw, "status")
	}
	if v, ok := raw["tags"]; ok {
		if err := json.Unmarshal(v, &out.Tags); err != nil {
			return fmt.Errorf("decode %q: %w", "tags", err)
		}
		delete(raw, "tags")
	}
	if v, ok := raw["parent"]; ok {
		if err := json.Unmarshal(v, &out.Parent); err != nil {
			return fmt.Errorf("decode %q: %w", "parent", err)
		}
		delete(raw, "parent")
	}
	if v, ok := raw["shape"]; ok {
		if err := json.Unmarshal(v, &out.Shape); err != nil {
			return fmt.Errorf("decode %q: %w", "shape", err)
		}
		delete(raw, "shape")
	}
	if v, ok := raw["at"]; ok {
		if err := json.Unmarshal(v, &out.At); err != nil {
			return fmt.Errorf("decode %q: %w", "at", err)
		}
		delete(raw, "at")
	}
	if len(raw) > 0 {
		out.AdditionalProps = make(map[string]any, len(raw))
		for _, k := range sortedKeys(raw) {
			var e any
			if err := json.Unmarshal(raw[k], &e); err != nil {
				return fmt.Errorf("decode %q: %w", k, err)
			}
			out.AdditionalProps[k] = e
		}
	}
	*s = out
	return nil
}

// Validate reports the first constraint s does not satisfy.
func (s Pet) Validate() error {
	if v0, ok := s.Age.Get(); ok {
		if v0 < 0 {
			return errors.New(".age: must be at least 0")
		}
	}
	if v0, ok := s.Tags.Get(); ok {
		if len(v0) > 3 {
			return errors.New(".tags: must have at most 3 items")
		}
		for i1, v1 := range v0 {
			if err := v1.Validate(); err != nil {
				return fmt.Errorf(".tags[%d]: %w", i1, err)
			}
		}
	}
	if v0, ok := s.Parent.Get(); ok {
		if v0 != nil {
			if err := (*v0).Validate(); err != nil {
				return fmt.Errorf(".parent: %w", err)
			}
		}
	}
	if v0, ok := s.At.Get(); ok {
		if err := v0.Validate(); err != nil {
			return fmt.Errorf(".at: %w", err)
		}
	}
	return nil
}

type Point struct {
	F0 float64
	F1 float64
	F2 opt.Opt[string]
}

// MarshalJSON implements json.Marshaler.
func (s Point) MarshalJSON() ([]byte, error) {
	b := []byte{'['}
	n := 0
	if n > 0 {
		b = append(b, ',')
	}
	n++
	{
		d, err := json.Marshal(s.F0)
		if err != nil {
			return nil, fmt.Errorf("encode item 0: %w", err)
		}
		b = append(b, d...)
	}
	if n > 0 {
		b = append(b, ',')
	}
	n++
	{
		d, err := json.Marshal(s.F1)
		if err != nil {
			return nil, fmt.Errorf("encode item 1: %w", err)
		}
		b = append(b, d...)
	}
	if v, ok := s.F2.Get(); ok {
		if n > 0 {
			b = append(b, ',')
		}
		n++
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode item 2: %w", err)
			}
			b = append(b, d...)
		}
	} else if n < 2 {
		return nil, fmt.Errorf("item 2 is set but item %d is not; an array has no gap", n)
	}
	b = append(b, ']')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *Point) UnmarshalJSON(data []byte) error {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var out Point
	if len(raw) > 0 {
		if err := json.Unmarshal(raw[0], &out.F0); err != nil {
			return fmt.Errorf("decode item 0: %w", err)
		}
	} else {
		return fmt.Errorf("missing item 0")
	}
	if len(raw) > 1 {
		if err := json.Unmarshal(raw[1], &out.F1); err != nil {
			return fmt.Errorf("decode item 1: %w", err)
		}
	} else {
		return fmt.Errorf("missing item 1")
	}
	if len(raw) > 2 {
		if err := json.Unmarshal(raw[2], &out.F2); err != nil {
			return fmt.Errorf("decode item 2: %w", err)
		}
	}
	if len(raw) > 3 {
		return fmt.Errorf("expected at most 3 items, got %d", len(raw))
	}
	*s = out
	return nil
}

// Validate reports the first constraint s does not satisfy.
func (s Point) Validate() error {
	{
		count := 0
		count++
		count++
		if s.F2.IsSet() {
			count++
		}
		if count < 2 {
			return errors.New("must have at least 2 items")
		}
	}
	return nil
}

type Shape map[string]any

// The 2 values Shape admits have no distinct Go constant names.

// UnmarshalJSON implements json.Unmarshaler.
func (v *Shape) UnmarshalJSON(data []byte) error {
	canon, err := canonicalJSON(data)
	if err != nil {
		return err
	}
	switch canon {
	case "{\"kind\":\"circle\",\"r\":1}", "{\"kind\":\"square\",\"side\":2}":
	default:
		return fmt.Errorf("%s is not an admitted Shape", data)
	}
	var out map[string]any
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	*v = Shape(out)
	return nil
}

type Status string

// The values Status admits.
const (
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
)

// UnmarshalJSON implements json.Unmarshaler. Go constants restrict nothing,
// so this is where the admitted values are enforced.
func (v *Status) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "active", "archived":
		*v = Status(raw)
		return nil
	default:
		return fmt.Errorf("%v is not a valid Status", raw)
	}
}

type Tag struct {
	Name  string           `json:"name"`
	Score opt.Opt[float64] `json:"score,omitzero"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *Tag) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var out Tag
	if v, ok := raw["name"]; ok {
		if err := json.Unmarshal(v, &out.Name); err != nil {
			return fmt.Errorf("decode %q: %w", "name", err)
		}
		delete(raw, "name")
	} else {
		return fmt.Errorf("missing required property %q", "name")
	}
	if v, ok := raw["score"]; ok {
		if err := json.Unmarshal(v, &out.Score); err != nil {
			return fmt.Errorf("decode %q: %w", "score", err)
		}
		delete(raw, "score")
	}
	if len(raw) > 0 {
		return fmt.Errorf("unexpected property %q", sortedKeys(raw)[0])
	}
	*s = out
	return nil
}

// Validate reports the first constraint s does not satisfy.
func (s Tag) Validate() error {
	if utf8.RuneCountInString(string(s.Name)) < 1 {
		return errors.New(".name: must be at least 1 character")
	}
	if v0, ok := s.Score.Get(); ok {
		if v0 < 0.0 {
			return errors.New(".score: must be at least 0")
		}
		if v0 > 10.0 {
			return errors.New(".score: must be at most 10")
		}
	}
	return nil
}

// Not enforced by the generated validators:
//       1 kind selects a branch nothing generated evaluates

func encodeKey(b []byte, n *int, k string) ([]byte, error) {
	if *n > 0 {
		b = append(b, ',')
	}
	*n++
	key, err := json.Marshal(k)
	if err != nil {
		return nil, err
	}
	b = append(b, key...)
	return append(b, ':'), nil
}

// sortedKeys orders map iteration, so encoding a value twice produces the same bytes.
func sortedKeys[T any](m map[string]T) []string {
	return slices.Sorted(maps.Keys(m))
}

// canonicalJSON re-encodes a value in one form, so two spellings of the same JSON compare
// equal: object keys sort and numbers take a single format.
func canonicalJSON(data []byte) (string, error) {
	var v any
	if err := json.Unmarshal(data, &v); err != nil {
		return "", err
	}
	out, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(out), nil
}
