// Code generated by schemacompiler. DO NOT EDIT.

package gentest

import (
	"encoding/json"
	"fmt"
	"maps"
	"slices"

	"github.com/ogen-go/schemacompiler/opt"
)

// Pet is a pet.
type Pet struct {
	Name     string               `json:"name"`
	Age      opt.Opt[int64]       `json:"age,omitempty"`
	Nickname opt.Nullable[string] `json:"nickname"`
	Status   opt.Opt[Status]      `json:"status,omitempty"`
	Tags     opt.Opt[[]Tag]       `json:"tags,omitempty"`
	Parent   opt.Opt[*Pet]        `json:"parent,omitempty"`
	// AdditionalProps holds the properties no field and no pattern covers.
	AdditionalProps map[string]any
}

// MarshalJSON implements json.Marshaler.
func (s Pet) MarshalJSON() ([]byte, error) {
	b := []byte{'{'}
	n := 0
	var err error
	if b, err = encodeKey(b, &n, "name"); err != nil {
		return nil, err
	}
	{
		d, err := json.Marshal(s.Name)
		if err != nil {
			return nil, fmt.Errorf("encode %q: %w", "name", err)
		}
		b = append(b, d...)
	}
	if v, ok := s.Age.Get(); ok {
		if b, err = encodeKey(b, &n, "age"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "age", err)
			}
			b = append(b, d...)
		}
	}
	if b, err = encodeKey(b, &n, "nickname"); err != nil {
		return nil, err
	}
	{
		d, err := json.Marshal(s.Nickname)
		if err != nil {
			return nil, fmt.Errorf("encode %q: %w", "nickname", err)
		}
		b = append(b, d...)
	}
	if v, ok := s.Status.Get(); ok {
		if b, err = encodeKey(b, &n, "status"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "status", err)
			}
			b = append(b, d...)
		}
	}
	if v, ok := s.Tags.Get(); ok {
		if b, err = encodeKey(b, &n, "tags"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "tags", err)
			}
			b = append(b, d...)
		}
	}
	if v, ok := s.Parent.Get(); ok {
		if b, err = encodeKey(b, &n, "parent"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "parent", err)
			}
			b = append(b, d...)
		}
	}
	for _, k := range sortedKeys(s.AdditionalProps) {
		if b, err = encodeKey(b, &n, k); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(s.AdditionalProps[k])
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", k, err)
			}
			b = append(b, d...)
		}
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *Pet) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var out Pet
	if v, ok := raw["name"]; ok {
		if err := json.Unmarshal(v, &out.Name); err != nil {
			return fmt.Errorf("decode %q: %w", "name", err)
		}
		delete(raw, "name")
	} else {
		return fmt.Errorf("missing required property %q", "name")
	}
	if v, ok := raw["age"]; ok {
		if err := json.Unmarshal(v, &out.Age); err != nil {
			return fmt.Errorf("decode %q: %w", "age", err)
		}
		delete(raw, "age")
	}
	if v, ok := raw["nickname"]; ok {
		if err := json.Unmarshal(v, &out.Nickname); err != nil {
			return fmt.Errorf("decode %q: %w", "nickname", err)
		}
		delete(raw, "nickname")
	} else {
		return fmt.Errorf("missing required property %q", "nickname")
	}
	if v, ok := raw["status"]; ok {
		if err := json.Unmarshal(v, &out.Status); err != nil {
			return fmt.Errorf("decode %q: %w", "status", err)
		}
		delete(raw, "status")
	}
	if v, ok := raw["tags"]; ok {
		if err := json.Unmarshal(v, &out.Tags); err != nil {
			return fmt.Errorf("decode %q: %w", "tags", err)
		}
		delete(raw, "tags")
	}
	if v, ok := raw["parent"]; ok {
		if err := json.Unmarshal(v, &out.Parent); err != nil {
			return fmt.Errorf("decode %q: %w", "parent", err)
		}
		delete(raw, "parent")
	}
	if len(raw) > 0 {
		out.AdditionalProps = make(map[string]any, len(raw))
		for _, k := range sortedKeys(raw) {
			var e any
			if err := json.Unmarshal(raw[k], &e); err != nil {
				return fmt.Errorf("decode %q: %w", k, err)
			}
			out.AdditionalProps[k] = e
		}
	}
	*s = out
	return nil
}

type Status string

// The values Status admits.
const (
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
)

// UnmarshalJSON implements json.Unmarshaler. Go constants restrict nothing,
// so this is where the admitted values are enforced.
func (v *Status) UnmarshalJSON(data []byte) error {
	var raw string
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	switch raw {
	case "active", "archived":
		*v = Status(raw)
		return nil
	default:
		return fmt.Errorf("%v is not a valid Status", raw)
	}
}

type Tag struct {
	Name  string           `json:"name"`
	Score opt.Opt[float64] `json:"score,omitempty"`
}

// MarshalJSON implements json.Marshaler.
func (s Tag) MarshalJSON() ([]byte, error) {
	b := []byte{'{'}
	n := 0
	var err error
	if b, err = encodeKey(b, &n, "name"); err != nil {
		return nil, err
	}
	{
		d, err := json.Marshal(s.Name)
		if err != nil {
			return nil, fmt.Errorf("encode %q: %w", "name", err)
		}
		b = append(b, d...)
	}
	if v, ok := s.Score.Get(); ok {
		if b, err = encodeKey(b, &n, "score"); err != nil {
			return nil, err
		}
		{
			d, err := json.Marshal(v)
			if err != nil {
				return nil, fmt.Errorf("encode %q: %w", "score", err)
			}
			b = append(b, d...)
		}
	}
	b = append(b, '}')
	return b, nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (s *Tag) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	var out Tag
	if v, ok := raw["name"]; ok {
		if err := json.Unmarshal(v, &out.Name); err != nil {
			return fmt.Errorf("decode %q: %w", "name", err)
		}
		delete(raw, "name")
	} else {
		return fmt.Errorf("missing required property %q", "name")
	}
	if v, ok := raw["score"]; ok {
		if err := json.Unmarshal(v, &out.Score); err != nil {
			return fmt.Errorf("decode %q: %w", "score", err)
		}
		delete(raw, "score")
	}
	if len(raw) > 0 {
		return fmt.Errorf("unexpected property %q", sortedKeys(raw)[0])
	}
	*s = out
	return nil
}

func encodeKey(b []byte, n *int, k string) ([]byte, error) {
	if *n > 0 {
		b = append(b, ',')
	}
	*n++
	key, err := json.Marshal(k)
	if err != nil {
		return nil, err
	}
	b = append(b, key...)
	return append(b, ':'), nil
}

// sortedKeys orders map iteration, so encoding a value twice produces the same bytes.
func sortedKeys[T any](m map[string]T) []string {
	return slices.Sorted(maps.Keys(m))
}
