// Package gorun compiles a generated package and runs it.
//
// It exists for the assertion docs/backend.md §3 is about: what generated code *does* with
// an instance, which is the only thing that can join `planterp` and `nodetree` in the
// differential harness. Type-checking (internal/gotypecheck) says the package is legal Go
// and says nothing about whether it accepts the right documents.
//
// The package built here has no dependency outside the standard library: the presence types
// are copied in beside it rather than imported from this module, so the build needs no
// module cache, no network and no `replace` pointing back at a checkout.
package gorun

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/schemacompiler/gogen"
)

// Module is the module path of the built program, and OptPackage the import path its
// presence types land on. A caller renders against [OptPackage] so the generated source
// and the copied package agree.
const (
	Module     = "harness"
	OptPackage = Module + "/opt"
)

// Run writes files, main and a copy of optSrcDir into dir, then builds and runs the result
// with stdin on its input, returning what it wrote to standard output.
//
// A build failure is returned as an error carrying the compiler's own output: generated
// code that does not compile is the finding, not an obstacle to reporting one.
func Run(dir string, files []gogen.File, optSrcDir, main string, stdin []byte) ([]byte, error) {
	if err := write(dir, files, optSrcDir, main); err != nil {
		return nil, err
	}

	cmd := exec.Command("go", "run", ".")
	cmd.Dir = dir
	cmd.Stdin = bytes.NewReader(stdin)
	var out, errs bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errs
	if err := cmd.Run(); err != nil {
		return nil, errors.Wrapf(err, "go run: %s", strings.TrimSpace(errs.String()))
	}
	return out.Bytes(), nil
}

func write(dir string, files []gogen.File, optSrcDir, main string) error {
	goVersion, err := moduleGoVersion()
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"),
		[]byte("module "+Module+"\n\ngo "+goVersion+"\n"), 0o600); err != nil {
		return errors.Wrap(err, "write go.mod")
	}
	if err := copyPackage(optSrcDir, filepath.Join(dir, "opt")); err != nil {
		return errors.Wrap(err, "copy opt")
	}
	for _, f := range files {
		if err := os.WriteFile(filepath.Join(dir, f.Name), f.Content, 0o600); err != nil {
			return errors.Wrapf(err, "write %s", f.Name)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(main), 0o600); err != nil {
		return errors.Wrap(err, "write main.go")
	}
	return nil
}

// moduleGoVersion reads the language version this module is written against, so the built
// program is not held to a different one than the code it was generated by.
func moduleGoVersion() (string, error) {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.GoVersion}}").Output()
	if err != nil {
		return "", errors.Wrap(err, "read module go version")
	}
	v := strings.TrimSpace(string(out))
	if v == "" {
		return "", errors.New("module states no go version")
	}
	return v, nil
}

func copyPackage(src, dst string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return errors.Wrap(err, "read source")
	}
	if err := os.MkdirAll(dst, 0o750); err != nil {
		return errors.Wrap(err, "create destination")
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(src, name)) //nolint:gosec // a package path the caller names
		if err != nil {
			return errors.Wrapf(err, "read %s", name)
		}
		//nolint:gosec // name comes from a directory listing the caller named, not from input
		if err := os.WriteFile(filepath.Join(dst, filepath.Base(name)), data, 0o600); err != nil {
			return errors.Wrapf(err, "write %s", name)
		}
	}
	return nil
}
