package gogen_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/ogen-go/schemacompiler/gogen"
	"github.com/ogen-go/schemacompiler/internal/gotypecheck"
)

func render(t *testing.T, schema string) string {
	t.Helper()
	types, err := gogen.Lower(definitions(t, schema))
	require.NoError(t, err)
	files, err := gogen.Render(types, gogen.Options{})
	require.NoError(t, err)
	require.Len(t, files, 1)
	require.Equal(t, "types.go", files[0].Name)
	require.NoError(t, gotypecheck.Check(files, "../opt"))
	return string(files[0].Content)
}

func TestRender(t *testing.T) {
	got := render(t, `{
		"$defs":{"Pet":{
			"type":"object",
			"title":"A pet.",
			"description":"Something with a name.",
			"properties":{
				"name":{"type":"string","title":"The pet's name."},
				"age":{"type":"integer"},
				"legacy":{"type":"string","deprecated":true}
			},
			"required":["name"],
			"additionalProperties":false
		}},
		"type":"object","properties":{"p":{"$ref":"#/$defs/Pet"}}
	}`)

	require.Equal(t, "// Code generated by schemacompiler. DO NOT EDIT.\n"+
		"\n"+
		"package api\n"+
		"\n"+
		"import \"github.com/ogen-go/schemacompiler/opt\"\n"+
		"\n"+
		"// Pet is a pet.\n"+
		"// Something with a name.\n"+
		"type Pet struct {\n"+
		"\t// Name is the pet's name.\n"+
		"\tName string         `json:\"name\"`\n"+
		"\tAge  opt.Opt[int64] `json:\"age,omitempty\"`\n"+
		"\t// Deprecated: this schema is marked deprecated.\n"+
		"\tLegacy opt.Opt[string] `json:\"legacy,omitempty\"`\n"+
		"}\n", got)

	// Fields keep the order the schema declared them in, and a property with no title and
	// no description gets no comment rather than an empty one.
	require.Less(t, strings.Index(got, "Name "), strings.Index(got, "Age "))
}

func TestRenderOptions(t *testing.T) {
	types, err := gogen.Lower(definitions(t,
		`{"$defs":{"T":{"type":"object","properties":{"a":{"type":"string"}}}},"$ref":"#/$defs/T"}`))
	require.NoError(t, err)

	files, err := gogen.Render(types, gogen.Options{Package: "models", OptPackage: "example.com/x/opt"})
	require.NoError(t, err)
	src := string(files[0].Content)
	require.Contains(t, src, "package models\n")
	require.Contains(t, src, `import "example.com/x/opt"`)
}

// TestRenderOmitsTheImportWhenUnused keeps generated code compiling: an unused import is a
// compile error in Go, not a warning.
func TestRenderOmitsTheImportWhenUnused(t *testing.T) {
	src := render(t, `{"$defs":{"T":{"type":"string"}},"$ref":"#/$defs/T"}`)
	require.NotContains(t, src, "import")
	require.Contains(t, src, "type T string")
}

func TestRenderIsReproducible(t *testing.T) {
	defs := definitions(t, `{
		"$defs":{
			"A":{"type":"object","properties":{"b":{"$ref":"#/$defs/B"}}},
			"B":{"type":"object","properties":{"a":{"$ref":"#/$defs/A"}}}
		},
		"type":"object","properties":{"a":{"$ref":"#/$defs/A"}}
	}`)
	types, err := gogen.Lower(defs)
	require.NoError(t, err)
	first, err := gogen.Render(types, gogen.Options{})
	require.NoError(t, err)
	for range 16 {
		again, err := gogen.Render(types, gogen.Options{})
		require.NoError(t, err)
		require.Equal(t, string(first[0].Content), string(again[0].Content))
	}
}

// TestRenderKeepsPatternsAsComments records the gap: a pattern routes keys at runtime, and
// until there is a decoder to route them the Go type cannot say so on its own.
func TestRenderKeepsPatternsAsComments(t *testing.T) {
	src := render(t, `{"$defs":{"T":{"type":"object",
		"properties":{"a":{"type":"string"}},"required":["a"],
		"patternProperties":{"^x":{"type":"number"}},"additionalProperties":false}},
		"$ref":"#/$defs/T"}`)
	require.Contains(t, src, `Pattern0Props holds the properties matching "^x"`)
	require.Contains(t, src, "Pattern0Props map[string]float64")
}

// TestRenderSumsAsAny records the other gap: a sum needs a discriminator to be worth more
// than `any`, and dispatch is not lowered yet. The alternatives stay in a comment so the
// shape is not lost, and the validation plan still narrows what is accepted.
func TestRenderSumsAsAny(t *testing.T) {
	src := render(t, `{"$defs":{"T":{"oneOf":[{"type":"string"},{"type":"boolean"}]}},"$ref":"#/$defs/T"}`)
	require.Contains(t, src, "type T any")
	require.Contains(t, src, "// T is one of: string, bool.")
}

func TestRenderEveryVariant(t *testing.T) {
	for _, v := range gogen.AllGoTypes() {
		require.NotPanics(t, func() { _ = gogen.TypeExpr(v) })
	}
	files, err := gogen.Render([]*gogen.Named{
		{ID: "/$defs/A", Name: "A", Underlying: &gogen.Never{}},
		{ID: "/$defs/B", Name: "B", Underlying: &gogen.Tuple{Elems: []gogen.GoType{str()}, Rest: anyT()}},
	}, gogen.Options{})
	require.NoError(t, err)
	require.NoError(t, gotypecheck.Check(files, "../opt"))
	require.True(t, strings.Contains(string(files[0].Content), "type A struct{}"))
}
