package gogen

import (
	"fmt"
	"go/format"
	"slices"
	"strconv"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/schemacompiler/plan"
)

// DefaultOptPackage is the import path of the presence types generated fields are stored in.
const DefaultOptPackage = "github.com/ogen-go/schemacompiler/opt"

// Options configures rendering. Lowering takes none: none of its decisions are the
// caller's, and a knob that changed a shape per call would give two callers two Go types
// for one schema (docs/backend.md §0).
type Options struct {
	// Package is the generated package name. Defaults to "api".
	Package string
	// OptPackage is the import path of [DefaultOptPackage]'s replacement, for a caller
	// that vendors its own presence types. ogen does.
	OptPackage string
	// Codec asks for the JSON methods the types need beyond what [encoding/json] does on
	// its own. A type that needs none gets none; one whose codec is not written yet says
	// so in a comment rather than being left to encode wrongly in silence.
	Codec bool
	// Validate asks for the Validate method a type needs when its Go shape does not state
	// everything the schema does. A type whose shape states all of it gets none, and what
	// no check is written for yet is admitted in a comment (issue #161).
	Validate bool
}

// File is one generated source file.
type File struct {
	Name    string
	Content []byte
}

// Render writes types as Go source.
//
// It renders declarations only: what a value of each schema is stored as. Validation and
// encoding are separate outputs over the same types, and neither changes what is declared
// here.
func Render(types []*Named, opts Options) ([]File, error) {
	pkg := cmpOr(opts.Package, "api")
	optPkg := cmpOr(opts.OptPackage, DefaultOptPackage)

	body := renderer{optPkg: optPkg}
	var nodes map[*Named]*vnode
	var needs map[*Named]bool
	var unenforced map[string]int
	if opts.Validate {
		nodes, needs, unenforced = validators(types)
	}
	for _, n := range types {
		body.doc(n.Name, n.Metadata)
		body.variantNote(n.Name, n.Underlying)
		body.dispatchNote(n.Name, n.Checks.Dispatch)
		fmt.Fprintf(&body.b, "type %s ", n.Name)
		body.typ(n.Underlying)
		body.b.WriteString("\n\n")
		body.enumConsts(n)
		if opts.Codec {
			if why := body.codec(n); why != "" {
				fmt.Fprintf(&body.b, "// %s has no generated codec: %s.\n\n", n.Name, why)
			}
		}
		if opts.Validate && needs[n] {
			body.validator(n, nodes[n])
		}
	}
	if opts.Validate {
		body.unenforcedNote(unenforced)
	}
	for _, h := range helpers {
		if body.reached[h.name] {
			body.b.WriteString(h.src)
		}
	}

	var src strings.Builder
	src.WriteString("// Code generated by schemacompiler. DO NOT EDIT.\n\n")
	fmt.Fprintf(&src, "package %s\n\n", pkg)
	std, other := body.importGroups()
	writeImports(&src, std, other)
	src.WriteString(body.b.String())

	formatted, err := format.Source([]byte(src.String()))
	if err != nil {
		// The renderer produced something that is not Go. That is a bug here rather than
		// anything the caller did, and returning the text unformatted would hand it on
		// as a compile error in generated code with no hint where it came from.
		return nil, errors.Wrap(err, "format generated source")
	}
	return []File{{Name: "types.go", Content: formatted}}, nil
}

// writeImports keeps the standard library in its own group, which is where a Go author
// puts it and where `goimports` would move it back to.
func writeImports(src *strings.Builder, std, other []string) {
	switch {
	case len(std)+len(other) == 0:
		return
	case len(std)+len(other) == 1:
		fmt.Fprintf(src, "import %s\n\n", strconv.Quote(append(std, other...)[0]))
		return
	}
	src.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(src, "%s\n", strconv.Quote(p))
	}
	if len(std) > 0 && len(other) > 0 {
		src.WriteString("\n")
	}
	for _, p := range other {
		fmt.Fprintf(src, "%s\n", strconv.Quote(p))
	}
	src.WriteString(")\n\n")
}

func cmpOr(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// TypeExpr renders t as a Go type expression.
//
// It is the only rendering of a [GoType] there is, deliberately: a second one is a second
// answer to what a plan lowers to, and it is the one no compiler checks.
func TypeExpr(t GoType) string {
	var r renderer
	r.typ(t)
	return r.b.String()
}

// helpers are the blocks a generated file carries when something in it calls them, in the
// order they are written.
var helpers = []struct {
	name    string
	imports []string
	src     string
}{
	{name: "codec", imports: []string{"maps", "slices"}, src: codecHelpers},
	{name: "canon", src: canonHelper},
}

// renderer accumulates source and records what the writing reached for, so the import list
// and the helper blocks are decided by the same pass that writes the code needing them.
//
// Deciding either by a second walk of the types would be a second opinion about what got
// rendered, and an import Go does not see used is a compile error rather than a warning.
type renderer struct {
	b strings.Builder
	// optPkg is where the presence types are imported from, which the caller chooses.
	optPkg string
	// imports is the set of import paths reached for, reached is the set of helper names.
	imports map[string]bool
	reached map[string]bool
}

// need records an import the writer just reached for. An empty path is ignored, which is
// what a [TypeExpr] renderer with no configured presence package passes.
func (r *renderer) need(paths ...string) {
	for _, p := range paths {
		if p == "" {
			continue
		}
		if r.imports == nil {
			r.imports = map[string]bool{}
		}
		r.imports[p] = true
	}
}

// needHelper records a helper block the writer just called, along with what it imports.
func (r *renderer) needHelper(name string) {
	if r.reached == nil {
		r.reached = map[string]bool{}
	}
	r.reached[name] = true
	for _, h := range helpers {
		if h.name == name {
			r.need(h.imports...)
		}
	}
}

// importGroups splits what was reached for into the standard library and everything else,
// which is where a Go author puts them and where `goimports` would move them back to. A
// path whose first segment carries a dot names a host, so it is not the standard library.
func (r *renderer) importGroups() (std, other []string) {
	for p := range r.imports {
		host, _, _ := strings.Cut(p, "/")
		if strings.Contains(host, ".") {
			other = append(other, p)
			continue
		}
		std = append(std, p)
	}
	slices.Sort(std)
	slices.Sort(other)
	return std, other
}

func (r *renderer) typ(t GoType) {
	b := &r.b
	switch t := t.(type) {
	case *Named:
		b.WriteString(t.Name)
	case *Pointer:
		b.WriteString("*")
		r.typ(t.Elem)
	case *Slice:
		b.WriteString("[]")
		r.typ(t.Elem)
	case *Map:
		b.WriteString("map[string]")
		r.typ(t.Elem)
	case *Presence:
		r.need(r.optPkg)
		b.WriteString("opt.")
		switch {
		case t.Optional && t.Nullable:
			b.WriteString("OptNullable[")
		case t.Optional:
			b.WriteString("Opt[")
		default:
			b.WriteString("Nullable[")
		}
		r.typ(t.Elem)
		b.WriteString("]")
	case *Struct:
		r.strukt(t)
	case *Tuple:
		r.tuple(t)
	case *Enum:
		// An enum is stored as its element; the literals are constants beside the
		// declaration, and a decoder is what makes them the only admitted values.
		r.typ(t.Elem)
	case *Interface:
		// A sum needs a discriminator to be worth more than this, and dispatch is not
		// lowered yet. `any` accepts every alternative, which over-accepts in the one
		// direction design §24 permits, and the validation plan still narrows it.
		//
		// The alternatives are named by [variantNote] wherever there is a doc comment to
		// put them in. They cannot go in the type: Go block comments do not nest, so a
		// sum of a sum would have its first `*/` close both.
		_ = t
		b.WriteString("any")
	case *Primitive:
		b.WriteString(goPrimitive(t.Kind))
	case *Any:
		b.WriteString("any")
	case *Never:
		b.WriteString("struct{}")
	default:
		panic(fmt.Sprintf("gogen: unhandled GoType variant %T", t))
	}
}

func (r *renderer) strukt(t *Struct) {
	b := &r.b
	if len(t.Fields) == 0 && len(t.Patterns) == 0 && t.Additional == nil {
		b.WriteString("struct{}")
		return
	}

	b.WriteString("struct {\n")
	slots := slotsOf(t)
	for _, f := range t.Fields {
		r.doc(f.Name, f.Metadata)
		r.variantNote(f.Name, f.Type)
		fmt.Fprintf(b, "%s ", f.Name)
		r.typ(f.Type)
		fmt.Fprintf(b, " `json:%s`\n", strconv.Quote(jsonTag(f)))
	}
	for i, p := range t.Patterns {
		name := slots.Patterns[i]
		fmt.Fprintf(b, "// %s holds the properties matching %s.\n", name, strconv.Quote(p.Pattern))
		fmt.Fprintf(b, "%s map[string]", name)
		r.typ(p.Elem)
		b.WriteString("\n")
	}
	if t.Additional != nil {
		name := slots.Additional
		fmt.Fprintf(b, "// %s holds the properties no field and no pattern covers.\n", name)
		fmt.Fprintf(b, "%s map[string]", name)
		r.typ(t.Additional)
		b.WriteString("\n")
	}
	b.WriteString("}")
}

func (r *renderer) tuple(t *Tuple) {
	b := &r.b
	if len(t.Elems) == 0 && t.Rest == nil {
		b.WriteString("struct{}")
		return
	}

	b.WriteString("struct {\n")
	slots := slotsOfTuple(t)
	for i, e := range t.Elems {
		fmt.Fprintf(b, "%s ", slots.Elems[i])
		r.typ(e)
		b.WriteString("\n")
	}
	if t.Rest != nil {
		fmt.Fprintf(b, "%s []", slots.Rest)
		r.typ(t.Rest)
		b.WriteString("\n")
	}
	b.WriteString("}")
}

// jsonTag is the property name plus `omitzero` for a field that may be absent.
//
// Not `omitempty`: that does nothing at all for a struct type, so an unset [opt.Opt] would
// be written as its own zero value rather than left out. `omitzero` (Go 1.24) consults the
// field's `IsZero` method, which is why [opt.Opt] and [opt.OptNullable] have one and
// [opt.Nullable] deliberately does not — its zero is null, and null is written.
func jsonTag(f Field) string {
	if p, ok := f.Type.(*Presence); ok && p.Optional {
		return f.JSON + ",omitzero"
	}
	return f.JSON
}

// writeDoc renders the schema's annotations as godoc, led by the identifier so the comment
// reads the way Go's own do. `title` is documentation here and never a name (§1).
func (r *renderer) doc(name string, m plan.Metadata) {
	b := &r.b
	var lines []string
	if m.Title != "" {
		lines = append(lines, name+" is "+lowerFirst(strings.TrimSuffix(m.Title, "."))+".")
	}
	for _, l := range strings.Split(m.Description, "\n") {
		if l = strings.TrimSpace(l); l != "" {
			lines = append(lines, l)
		}
	}
	if m.Deprecated {
		if len(lines) > 0 {
			lines = append(lines, "")
		}
		lines = append(lines, "Deprecated: this schema is marked deprecated.")
	}
	for _, l := range lines {
		if l == "" {
			b.WriteString("//\n")
			continue
		}
		b.WriteString("// " + l + "\n")
	}
}

// enumConsts declares the literals of a named enum.
//
// Only a named one gets them: an enum nested in a field has no declaration to hang
// constants off. It keeps its values in the plan either way, so what is lost there is the
// spelling and not the constraint.
func (r *renderer) enumConsts(n *Named) {
	e, ok := n.Underlying.(*Enum)
	if !ok {
		return
	}
	lits := make([]string, len(e.Values))
	taken := make(map[string]bool, len(e.Values))
	for i, v := range e.Values {
		lit, ok := goLiteral(v, e.Elem)
		name := n.Name + v.Name
		// All or nothing, and the type is correct either way. A partial constant set is
		// worse than none: it reads as the whole admitted set while being a subset of it.
		// Two literals that spell one identifier — `1` and `-1`, `1.5` and `15` — are a
		// refusal for the same reason a colliding type name is (§1).
		if !ok || v.Name == "" || checkIdentifier(name) != nil || taken[name] {
			fmt.Fprintf(&r.b, "// The %d values %s admits have no distinct Go constant names.\n\n",
				len(e.Values), n.Name)
			return
		}
		taken[name] = true
		lits[i] = lit
	}

	fmt.Fprintf(&r.b, "// The values %s admits.\nconst (\n", n.Name)
	for i, v := range e.Values {
		fmt.Fprintf(&r.b, "%s%s %s = %s\n", n.Name, v.Name, n.Name, lits[i])
	}
	r.b.WriteString(")\n\n")
}

// goLiteral is the Go source for one admitted value, or false when it has none.
func goLiteral(v EnumValue, elem GoType) (string, bool) {
	p, ok := deref(elem).(*Primitive)
	if !ok {
		return "", false
	}
	switch p.Kind {
	case PrimitiveString:
		s, ok := v.Value.(string)
		return strconv.Quote(s), ok
	case PrimitiveBool:
		b, ok := v.Value.(bool)
		return strconv.FormatBool(b), ok
	case PrimitiveInt, PrimitiveFloat:
		// A JSON number is already Go's spelling of one, so the document's own bytes are
		// the literal — which is what keeps a value past float64's precision exact.
		text, ok := numericText(v.Value, v.Raw)
		if !ok {
			return "", false
		}
		if p.Kind == PrimitiveInt {
			// The element type has to be able to hold it. A document may write an
			// integer past int64, and an untyped constant that overflows its type is a
			// compile error rather than a rounded value.
			if _, err := strconv.ParseInt(text, 10, 64); err != nil {
				return "", false
			}
		}
		return text, true
	default:
		return "", false
	}
}

// writeVariantNote names the alternatives of a sum, which renders as `any` until dispatch
// is lowered. A sum nested deeper than a declaration or a field has no comment to carry
// this, and loses it; the plan keeps it either way.
func (r *renderer) variantNote(name string, t GoType) {
	b := &r.b
	sum, ok := deref(t).(*Interface)
	if !ok {
		return
	}
	alts := make([]string, len(sum.Variants))
	for i, v := range sum.Variants {
		alts[i] = strings.Join(strings.Fields(TypeExpr(v)), " ")
	}
	fmt.Fprintf(b, "// %s is one of: %s.\n", name, strings.Join(alts, ", "))
}

// dispatchNote admits that the plan selects a branch and nothing generated does
// (docs/backend.md §14). It is a line comment for the reason [variantNote] is: Go block
// comments do not nest.
func (r *renderer) dispatchNote(name string, d DispatchCheck) {
	if d.Disposition == Discharged {
		return
	}
	fmt.Fprintf(&r.b, "// %s has an unenforced %s dispatch: nothing generated selects a branch, so every alternative is admitted.\n",
		name, d.Kind)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	// Only a single leading capital is lowered: `HTTP proxy` is not `hTTP proxy`.
	if len(r) > 1 && r[1] >= 'A' && r[1] <= 'Z' {
		return s
	}
	return strings.ToLower(string(r[0])) + string(r[1:])
}

// freeName keeps a generated slot clear of the declared fields it sits beside. A schema may
// well declare a property called `additionalProps`.
func freeName(want string, taken map[string]bool) string {
	for taken[want] {
		want += "_"
	}
	return want
}

func goPrimitive(k PrimitiveKind) string {
	switch k {
	case PrimitiveString:
		return "string"
	case PrimitiveBool:
		return "bool"
	case PrimitiveInt:
		return "int64"
	case PrimitiveFloat:
		return "float64"
	case PrimitiveNull:
		return "struct{}"
	default:
		panic(fmt.Sprintf("gogen: unhandled PrimitiveKind %v", k))
	}
}
